---
title: "Simulation"
author: "Yi Zhou"
date: "April 27, 2016"
fontsize: 14pt
output: pdf_document
---
```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(knitr); library(stargazer)
opts_chunk$set(echo = TRUE, cache = TRUE,
               warning=FALSE, message=FALSE, results="asis", 
               comment = c("#"), 
               fig.height=4, fig.width=4)
options(digits=7)
```

```{r, results='asis'}
avg.slope <- function(n1, m1, s1, b01,
                      n2, m2, s2, b02){
  
## group 1
X1 <- rnorm(n1, mean = m1, sd = s1)
Y1 <- 2*X1 + b01 + rnorm(10, sd = 0.1)

## group 2
X2 <- rnorm(n2, mean = m2, sd = s2)
Y2 <- 2*X2 + b02 + rnorm(10, sd = 0.1)

## model 
f1 <- lm(Y1~X1);  f1
f2 <- lm(Y2~X2);  f2

## pooled data
dd <- data.frame(X = c(X1, X2), Y = c(Y1, Y2))
fit <- lm(Y~X, data = dd);  fit

stargazer::stargazer(f1, f2, fit, no.space=TRUE)
## weighted average slope
b <- ((n1-1)*var(X1)*f1$coefficients[2]
      + (n2-1)*var(X2)*f2$coefficients[2])/((n1-1)*var(X1) 
                                        + (n2-1)*var(X2))
b0<- (sum((X1-mean(X1))^2)*f1$coefficients[2] 
      + sum((X2-mean(X2))^2)*f2$coefficients[2])/(sum((X1-mean(X1))^2) 
                                                  + sum((X2-mean(X2))^2))

b1 <- (sum((X1-mean(X1))*(Y1-mean(Y1)))
      + sum((X2-mean(X2))*(Y2-mean(Y2))))/(sum((X1-mean(X1))^2) 
                                           + sum((X2-mean(X2))^2))
## coefficients
com <- list(b = b, b0 = b0, b1 = b1, coef = fit$coefficients[2])

## plot
plot(dd$X, dd$Y)
abline(fit)           ## black line
abline(0, b, col = 2) ## red line

return(com)
}

```

\newpage

```{r}
avg.slope(10, 2, 1, 0, 
          10, 4, 1, 0)

avg.slope(20, 2, 1, 1, 
          20, 4, 1, 5)

avg.slope(100, 20, 1, 5, 
          100, 40, 1, 5)

```

